import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import axios from 'axios';
import { useState } from 'react';
import Link from 'next/link';
import NavBar from '@/components/NavBar';
import ScrollToTop from 'react-scroll-to-top';

export default function Home() {
  const [data,setData] = useState()

  const api_key = process.env.NEXT_NASA_API_KEY
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${api_key}`
  const getTechTransferData = async () => {
    const res = await axios.get(url);
    console.log(res.data);
    const info = await res.data;
    setData(info);
  }
useEffect(()=>{
  getTechTransferData()
}, [])

function generateRandomNumber() {
  return Math.floor(Math.random() * (350 - 175 + 1) + 175);
}
let dimension = generateRandomNumber();
return (
  <>
    <Head>
      <title>Nasa Data</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <NavBar/>
      <div className='gallery'>
      {
        data && data.results.map((tech, index) =>{
          return(
            <div key={index}>
                {
                  tech && tech.map((t, ind) =>{

                    if (ind === 10) {
                      dimension = generateRandomNumber();
                      return(
                        <Image src={t} alt={t} key={ind} width={dimension} height={dimension} />
                      )
                    }
                  })
                }
            </div>
          )
        })
      }
      <ScrollToTop smooth />
      </div>
    </main>
  </>
)
}
